[shlvl]
disabled = false

[hostname]
ssh_only = false
disabled = false

[conda]
truncation_length = 2

[custom.chezmoi]
command = "echo chezmoi"
when = "test -n \"$CHEZMOI\""
format = "[in $output]($style) "
style = "bold blue"
