.ONESHELL:

PREFIX=${HOME}/.local
export PREFIX

all:
	$(MAKE) -C libevent all
	$(MAKE) -C ncurses all
	$(MAKE) -C tmux all
	$(MAKE) -C mambaforge all
	$(MAKE) -C golang all


clean:
	$(MAKE) -C libevent clean
	$(MAKE) -C ncurses clean
	$(MAKE) -C tmux clean
	$(MAKE) -C mambaforge clean
	$(MAKE) -C golang clean



# tap "homebrew/bundle"
#tap "homebrew/core"
#brew "bat"
#brew "broot"
#brew "exa"
#brew "fd"
#brew "fzf"
#brew "git"
#brew "glow"
#brew "htop"
#brew "lazygit"
#brew "neovim"
#brew "ripgrep"
#brew "tldr"
#brew "cmake"
#brew "icdiff"
#brew "zoxide"
#brew "dust"
#brew "duf"
#brew "mcfly"

#brew "python"
#brew "mypy"
#brew "isort"
#brew "black"
#brew "pyright"


#tap "go-task/homebrew-tap"
#brew "go-task"

#tap "hhoeflin/tap"
#brew "zotero"
#brew "buildg"
